<?php
declare(strict_types=1);

return [
    'skills' => [
        'table' => 'skills',
        'singular' => 'Skill',
        'plural' => 'Skills',
        'order' => 'sort_order ASC, name ASC',
        'fields' => [
            ['name' => 'name', 'label' => 'Name', 'type' => 'text', 'required' => true, 'max' => 100],
            ['name' => 'category', 'label' => 'Category', 'type' => 'text', 'required' => true, 'max' => 80],
            ['name' => 'level', 'label' => 'Proficiency', 'type' => 'integer', 'required' => true, 'min' => 0, 'max_value' => 100],
            ['name' => 'sort_order', 'label' => 'Sort order', 'type' => 'integer', 'required' => true, 'min' => 0],
        ],
        'columns' => [
            ['key' => 'name', 'label' => 'Name'],
            ['key' => 'category', 'label' => 'Category'],
            ['key' => 'level', 'label' => 'Proficiency'],
            ['key' => 'sort_order', 'label' => 'Order'],
        ],
    ],
    'services' => [
        'table' => 'services',
        'singular' => 'Service',
        'plural' => 'Services',
        'order' => 'sort_order ASC, id ASC',
        'fields' => [
            ['name' => 'title', 'label' => 'Title', 'type' => 'text', 'required' => true, 'max' => 120],
            ['name' => 'description', 'label' => 'Description', 'type' => 'textarea', 'required' => true, 'max' => 50000],
            ['name' => 'icon', 'label' => 'Icon name', 'type' => 'text', 'required' => true, 'max' => 40],
            ['name' => 'sort_order', 'label' => 'Sort order', 'type' => 'integer', 'required' => true, 'min' => 0],
        ],
        'columns' => [
            ['key' => 'title', 'label' => 'Title'],
            ['key' => 'icon', 'label' => 'Icon'],
            ['key' => 'sort_order', 'label' => 'Order'],
        ],
    ],
    'projects' => [
        'table' => 'projects',
        'singular' => 'Project',
        'plural' => 'Projects',
        'order' => 'featured DESC, sort_order ASC, created_at DESC',
        'fields' => [
            ['name' => 'title', 'label' => 'Title', 'type' => 'text', 'required' => true, 'max' => 140],
            ['name' => 'slug', 'label' => 'Slug', 'type' => 'slug', 'required' => true, 'max' => 160],
            ['name' => 'summary', 'label' => 'Summary', 'type' => 'textarea', 'required' => true, 'max' => 2000],
            ['name' => 'description', 'label' => 'Description', 'type' => 'richtext', 'required' => true, 'max' => 100000],
            ['name' => 'image', 'label' => 'Project image', 'type' => 'image', 'upload_prefix' => 'project', 'accept' => 'image/jpeg,image/png,image/webp'],
            ['name' => 'technologies', 'label' => 'Technologies', 'type' => 'json', 'required' => true, 'max' => 5000],
            ['name' => 'demo_url', 'label' => 'Demo URL', 'type' => 'url', 'max' => 255],
            ['name' => 'source_url', 'label' => 'Source URL', 'type' => 'url', 'max' => 255],
            ['name' => 'featured', 'label' => 'Featured', 'type' => 'boolean'],
            ['name' => 'sort_order', 'label' => 'Sort order', 'type' => 'integer', 'required' => true, 'min' => 0],
        ],
        'columns' => [
            ['key' => 'title', 'label' => 'Project'],
            ['key' => 'featured', 'label' => 'Featured'],
            ['key' => 'technologies', 'label' => 'Technologies'],
            ['key' => 'created_at', 'label' => 'Created'],
        ],
    ],
    'experience' => [
        'table' => 'experience',
        'singular' => 'Experience',
        'plural' => 'Experience',
        'order' => 'sort_order ASC, start_date DESC',
        'fields' => [
            ['name' => 'company', 'label' => 'Company', 'type' => 'text', 'required' => true, 'max' => 140],
            ['name' => 'title', 'label' => 'Job title', 'type' => 'text', 'required' => true, 'max' => 140],
            ['name' => 'location', 'label' => 'Location', 'type' => 'text', 'max' => 140],
            ['name' => 'start_date', 'label' => 'Start date', 'type' => 'date', 'required' => true],
            ['name' => 'end_date', 'label' => 'End date', 'type' => 'date'],
            ['name' => 'current_job', 'label' => 'Current role', 'type' => 'boolean'],
            ['name' => 'description', 'label' => 'Description', 'type' => 'textarea', 'required' => true, 'max' => 50000],
            ['name' => 'sort_order', 'label' => 'Sort order', 'type' => 'integer', 'required' => true, 'min' => 0],
        ],
        'columns' => [
            ['key' => 'company', 'label' => 'Company'],
            ['key' => 'title', 'label' => 'Role'],
            ['key' => 'start_date', 'label' => 'Start'],
            ['key' => 'end_date', 'label' => 'End'],
            ['key' => 'current_job', 'label' => 'Current'],
        ],
    ],
    'education' => [
        'table' => 'education',
        'singular' => 'Education',
        'plural' => 'Education',
        'order' => 'sort_order ASC, graduation_year DESC',
        'fields' => [
            ['name' => 'institution', 'label' => 'Institution', 'type' => 'text', 'required' => true, 'max' => 160],
            ['name' => 'degree', 'label' => 'Degree', 'type' => 'text', 'required' => true, 'max' => 160],
            ['name' => 'field_of_study', 'label' => 'Field of study', 'type' => 'text', 'max' => 160],
            ['name' => 'graduation_year', 'label' => 'Graduation year', 'type' => 'year'],
            ['name' => 'description', 'label' => 'Description', 'type' => 'textarea', 'required' => true, 'max' => 50000],
            ['name' => 'sort_order', 'label' => 'Sort order', 'type' => 'integer', 'required' => true, 'min' => 0],
        ],
        'columns' => [
            ['key' => 'institution', 'label' => 'Institution'],
            ['key' => 'degree', 'label' => 'Degree'],
            ['key' => 'field_of_study', 'label' => 'Field'],
            ['key' => 'graduation_year', 'label' => 'Year'],
        ],
    ],
    'testimonials' => [
        'table' => 'testimonials',
        'singular' => 'Testimonial',
        'plural' => 'Testimonials',
        'order' => 'sort_order ASC, id ASC',
        'fields' => [
            ['name' => 'name', 'label' => 'Name', 'type' => 'text', 'required' => true, 'max' => 120],
            ['name' => 'role', 'label' => 'Role', 'type' => 'text', 'max' => 120],
            ['name' => 'message', 'label' => 'Message', 'type' => 'textarea', 'required' => true, 'max' => 50000],
            ['name' => 'avatar', 'label' => 'Avatar', 'type' => 'image', 'upload_prefix' => 'testimonial', 'accept' => 'image/jpeg,image/png,image/webp'],
            ['name' => 'sort_order', 'label' => 'Sort order', 'type' => 'integer', 'required' => true, 'min' => 0],
        ],
        'columns' => [
            ['key' => 'name', 'label' => 'Name'],
            ['key' => 'role', 'label' => 'Role'],
            ['key' => 'sort_order', 'label' => 'Order'],
        ],
    ],
    'messages' => [
        'table' => 'messages',
        'singular' => 'Message',
        'plural' => 'Messages',
        'order' => 'created_at DESC, id DESC',
        'fields' => [
            ['name' => 'name', 'label' => 'Name', 'type' => 'text', 'required' => true, 'max' => 120],
            ['name' => 'email', 'label' => 'Email', 'type' => 'email', 'required' => true, 'max' => 180],
            ['name' => 'subject', 'label' => 'Subject', 'type' => 'text', 'max' => 180],
            ['name' => 'message', 'label' => 'Message', 'type' => 'textarea', 'required' => true, 'max' => 50000],
            ['name' => 'is_read', 'label' => 'Mark as read', 'type' => 'boolean'],
        ],
        'columns' => [
            ['key' => 'name', 'label' => 'From'],
            ['key' => 'email', 'label' => 'Email'],
            ['key' => 'subject', 'label' => 'Subject'],
            ['key' => 'is_read', 'label' => 'Status'],
            ['key' => 'created_at', 'label' => 'Received'],
        ],
    ],
    'blog-posts' => [
        'table' => 'blog_posts',
        'singular' => 'Blog post',
        'plural' => 'Blog posts',
        'order' => 'created_at DESC, id DESC',
        'fields' => [
            ['name' => 'title', 'label' => 'Title', 'type' => 'text', 'required' => true, 'max' => 180],
            ['name' => 'slug', 'label' => 'Slug', 'type' => 'slug', 'required' => true, 'max' => 200],
            ['name' => 'excerpt', 'label' => 'Excerpt', 'type' => 'textarea', 'required' => true, 'max' => 5000],
            ['name' => 'content', 'label' => 'Content', 'type' => 'richtext', 'required' => true, 'max' => 100000],
            ['name' => 'featured_image', 'label' => 'Featured image', 'type' => 'image', 'upload_prefix' => 'blog', 'accept' => 'image/jpeg,image/png,image/webp'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'required' => true, 'options' => ['draft' => 'Draft', 'published' => 'Published']],
            ['name' => 'published_at', 'label' => 'Published at', 'type' => 'datetime'],
        ],
        'columns' => [
            ['key' => 'title', 'label' => 'Title'],
            ['key' => 'status', 'label' => 'Status'],
            ['key' => 'published_at', 'label' => 'Published'],
            ['key' => 'created_at', 'label' => 'Created'],
        ],
    ],
];
