<?php
$aboutTitle = tamim_setting('about_title', 'A developer who cares about the details.');
$aboutLead = tamim_setting('about_lead', '');
$aboutDescription = tamim_setting('about_description', '');
$location = tamim_setting('hero_location', 'Bangladesh');
$email = tamim_setting('hero_email', 'hello@tamim.dev');
?>
<section class="page-hero section-soft"><div class="container page-hero-grid"><div><p class="eyebrow">Hello, I am Tamim</p><h1><?php echo tamim_e($aboutTitle); ?></h1></div><div class="page-hero-art" aria-hidden="true"><div class="portrait-frame"><span>T</span><i></i><b></b></div><div class="portrait-badge">Web<br><strong>Developer</strong></div></div></div></section>
<section class="section"><div class="container about-story"><div class="about-image"><div class="image-panel panel-one"></div><div class="image-panel panel-two"></div><div class="image-caption"><strong>Built for the web.</strong><span>Designed around people.</span></div></div><div class="about-copy"><p class="eyebrow">My approach</p><h2><?php echo tamim_e($aboutLead); ?></h2><p class="lead"><?php echo tamim_e($aboutDescription); ?></p><p class="muted">I believe a successful website is more than a collection of pages. It is a clear conversation between a person and a purpose. That belief shapes how I plan, design, write and test every project.</p><div class="fact-grid"><div><strong>08+</strong><span>Years learning</span></div><div><strong>20+</strong><span>Projects shipped</span></div><div><strong>100%</strong><span>Ownership</span></div></div></div></div></section>
<section class="section section-tint"><div class="container principles-grid"><article><span>01</span><h3>Listen first</h3><p>Every useful product starts with the right question, not the fastest answer.</p></article><article><span>02</span><h3>Make it clear</h3><p>Good interfaces reduce friction and help people move forward with confidence.</p></article><article><span>03</span><h3>Build to last</h3><p>Clean structure and thoughtful defaults keep a product easy to change later.</p></article></div></section>
<section class="cta-section cta-section-soft"><div class="container cta-inner"><div><p class="eyebrow">Based in <?php echo tamim_e($location); ?></p><h2>Let us build something <em>worth sharing</em>.</h2></div><a class="button button-primary" href="mailto:<?php echo tamim_e($email); ?>">Send a message <span>↗</span></a></div></section>
